version: "4"
services:
  mysql:
    image: mysql:8.3.0
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: mysql_pwd
    ports:
      - "3306:3306"
    volumes:
      - ./volume_mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  volume_mysql_data:
